version: "2.10"
services:
  api:
    image: credit_flask_api
    container_name: ml_api
    build:
      context: ./api
      target: build
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    depends_on:
      - redis
      - model
    volumes:
      - ./uploads:/src/static/uploads

  model:
    image: credit_ml_service
    container_name: ml_model
    build:
      context: ./model
      target: build
    depends_on:
      - redis

  redis:
    image: redis:6.2.6
